version: '2.4'

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    hostname: mysql-db
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE=wordpress
    volumes:
      - ./dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
#    networks:
#      - app-network

  wordpress:
    depends_on:
      - db
    image: wordpress:6.8.1-fpm
    container_name: wordpress
    hostname: wordpress
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=mysql-db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
#      - WORDPRESS_CONFIG_EXTRA=define('WP_ALLOW_MULTISITE', true);
#      - WORDPRESS_CONFIG_EXTRA=define('MULTISITE', true);
#      - WORDPRESS_CONFIG_EXTRA=define('SUBDOMAIN_INSTALL', false);
#      - WORDPRESS_CONFIG_EXTRA=define('DOMAIN_CURRENT_SITE', 'domain.ir');
#      - WORDPRESS_CONFIG_EXTRA=define('PATH_CURRENT_SITE', '/');
#      - WORDPRESS_CONFIG_EXTRA=define('SITE_ID_CURRENT_SITE', 1);
#      - WORDPRESS_CONFIG_EXTRA=define('BLOG_ID_CURRENT_SITE', 1);
    volumes:
      - ./wordpress:/var/www/html
#    networks:
#      - app-network

  webserver:
    depends_on:
      - wordpress
    image: nginx:stable-alpine
    container_name: webserver
    hostname: webserver
    restart: unless-stopped
    ports:
      - "127.0.0.1:4444:443"
    volumes:
      - ./wordpress:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - ./certbot-etc:/etc/letsencrypt
#    networks:
#      - app-network

#  networks:
#    app-network:
#      driver: bridge
