version: '2.3'

services:
# nobody:nogroup user:group
  coturn:
    image: coturn/coturn:4.6.3
    restart: unless-stopped
    volumes:
      - ./coturn/data:/var/lib/coturn
      - ./coturn/domain.com.key:/etc/coturn/domain.com.key:ro
      - ./coturn/domain.com.crt:/etc/coturn/domain.com.crt:ro
      - ./coturn/turnserver.conf:/etc/coturn/turnserver.conf:ro
    ports:
      - 50100-50200:50100-50200/udp
      - 3478:3478/tcp
      - 3478:3478/udp
      - 5349:5349/udp
      - 5349:5349/tcp
    depends_on:
      - synapse

# 991:991 user:group
  synapse:
    image: ghcr.io/element-hq/synapse:latest
    hostname: synapseme
    restart: unless-stopped
    container_name: synapseme
    ports:
      - "127.0.0.1:8008:8008"
    environment:
      - SYNAPSE_CONFIG_PATH=/data/homeserver.yaml
    volumes:
      - ./element:/data
    depends_on:
      - db
#    networks:
#      default:
#        ipv4_address: 10.10.10.4

# systemd-coredump:systemd-coredump user:group
  db:
    image: docker.io/postgres:17.5-bookworm
    hostname: synapse-db
    restart: unless-stopped
    container_name: synapse-db
    environment:
      - POSTGRES_USER=synapse
      - POSTGRES_PASSWORD=synapseMainHelloHere
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - ./db:/var/lib/postgresql/data
#    networks:
#      default:
#        ipv4_address: 10.10.10.2
#  
#  element:
#    image: vectorim/element-web:latest
#    restart: unless-stopped
#    volumes:
#      - ./element-config.json:/app/config.json
#    networks:
#      default:
#        ipv4_address: 10.10.10.3
#networks:
#  default:
#    external:
#      name: matrix_server
